In [28]:
import pandas as pd
import shutil
import time
import requests
import json
import numpy as np
from IPython.display import clear_output
from IPython.display import display

In [29]:
start = 16500
end = 17500

In [30]:
strikes = np.arange(start,end+50,50)

In [31]:
df = pd.DataFrame(strikes, columns=['StrikePrice'])
df['Call-OI-Change'] = 0
df['Put-OI-Change'] = 0
df["Call-OI"] = 0
df['Put-OI'] = 0

In [32]:
df

    StrikePrice  Call-OI-Change  Put-OI-Change  Call-OI  Put-OI
0         16500               0              0        0       0
1         16550               0              0        0       0
2         16600               0              0        0       0
3         16650               0              0        0       0
4         16700               0              0        0       0
5         16750               0              0        0       0
6         16800               0              0        0       0
7         16850               0              0        0       0
8         16900               0              0        0       0
9         16950               0              0        0       0
10        17000               0              0        0       0
11        17050               0              0        0       0
12        17100               0              0        0       0
13        17150               0              0        0       0
14        17200               0              0        0       0
15        17250               0              0        0       0
16        17300               0              0        0       0
17        17350               0              0        0       0
18        17400               0              0        0       0
19        17450               0              0        0       0
20        17500               0              0        0       0
21        17550               0              0        0       0
22        17600               0              0        0       0
23        17650               0              0        0       0
24        17700               0              0        0       0
25        17750               0              0        0       0
26        17800               0              0        0       0
27        17850               0              0        0       0
28        17900               0              0        0       0
29        17950               0              0        0       0
30        18000               0              0        0       0

In [33]:
first_price = 0

In [34]:
    while True :
        new_url = 'https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY'
        headers = {'User-Agent': 'Mozilla/5.0'}
        page = requests.get(new_url,headers=headers)
        k = json.loads(page.text)
        ce = []
        pe = []
        for i in k['records']['data'] :
            if i['expiryDate'] == '23-Dec-2021' and i['strikePrice'] in strikes:
                ce.append(i['CE'])
                pe.append(i['PE'])
        spot_price = pe[0]['underlyingValue']
        
        ce_dataframe = pd.DataFrame(ce,columns=['strikePrice','openInterest'])
        pe_dataframe = pd.DataFrame(pe,columns=['strikePrice','openInterest'])
        ce_dataframe['Put-OI'] = pe_dataframe[['openInterest']]
        ce_dataframe['Call-OI-Change'] = 0
        ce_dataframe['Put-OI-Change'] = 0
        df_new = ce_dataframe.rename(columns = {'openInterest': 'Call-OI'}, inplace = False)
        df_answer = df_new.copy()
        ce_1 = df.loc[:,'Call-OI'].to_numpy()
        ce_2 = df_answer.loc[:,'Call-OI'].to_numpy()
        pe_1 = df.loc[:,'Put-OI'].to_numpy()
        pe_2 = df_answer.loc[:,'Put-OI'].to_numpy()
        ce_change = ce_2 - ce_1
        pe_change = pe_2 - pe_1
        df_answer['Call-OI-Change'] = pd.DataFrame(ce_change)
        df_answer['Put-OI-Change'] = pd.DataFrame(pe_change)
        df = df_answer.copy()
        clear_output()
        print("Spot Price = ", spot_price)
        print("Change Price = ", spot_price - first_price)
        first_price = spot_price
        display(df_answer)
        time.sleep(300)

Spot Price =  17069.6
Change Price =  9.5

    strikePrice  Call-OI  Put-OI  Call-OI-Change  Put-OI-Change
0         16500     1100   45070               1           -346
1         16550       23    6775               0            106
2         16600      121   30809              -2            138
3         16650       16    9162               0            -48
4         16700      444   33664              -6              0
5         16750      148    9326              -6            295
6         16800     3430   35492              -2            324
7         16850     1155   13667              15             80
8         16900     6352   32249              17            373
9         16950     3784   16647             -27            262
10        17000    59785   88250            -275            227
11        17050    17162   17443             -37            630
12        17100    63363   35153            -510            805
13        17150    18659    5959            -598            155
14        17200    95004   36750            -310           -255
15        17250    41304    6922             -49            -12
16        17300   116047   31421           -1354            -49
17        17350    26402    1476            -100             30
18        17400    88974    7496            -163             13
19        17450    20727     734            -261              2
20        17500   104757    9458           -1165            -88
21        17550    23275    1793            -462              0
22        17600    69920    2661             150              1
23        17650    19402     188            -465              0
24        17700    57497     791             -70             -3
25        17750    19570      87             -89              0
26        17800    50572    1195              37              1
27        17850    14408      96             -42              0
28        17900    61041     228              53              1
29        17950     7081      27             -33              0
30        18000   126648     886            -907              0

JSONDecodeError: Expecting value: line 1 column 1 (char 0)